alias ls='ls -al'
alias hosts='mate /etc/hosts'
alias getIP='wget -qO- http://ipecho.net/plain ; echo'
alias open-ports='lsof -i -P | grep -i "listen"'
alias ssh-copy-id='ssh-copy-id -i ~/.ssh/id_rsa.pub'
alias dangerclaude='claude --dangerously-skip-permissions'
alias dangerclaude-writer='claude --dangerously-skip-permissions --append-system-prompt-file ~/.claude/writing-style.md'
alias dodex='command codex --dangerously-bypass-approvals-and-sandbox'
alias dodex-writer='command codex --profile codex-lb-writer --dangerously-bypass-approvals-and-sandbox'
alias dodex-nadja='command codex --profile codex-lb-nadja --dangerously-bypass-approvals-and-sandbox'
alias subclaude='CLAUDE_CONFIG_DIR=~/.claude/profiles/sub claude --dangerously-skip-permissions'
